CREATE TABLE PARENTS
(
	ID SMALLINT,
	NAME VARCHAR(30),
	AGE TINYINT,
	PRIMARY KEY(ID)
);
CREATE TABLE CHILDREN
(
	PARENT_ID SMALLINT,
	NAME VARCHAR(30),
	AGE TINYINT,
	PRIMARY KEY(PARENT_ID, NAME),
	FOREIGN KEY (PARENT_ID) REFERENCES PARENTS(ID)
);
