CREATE TABLE PARENTS
(
	ID NUMBER(4),
	NAME VARCHAR2(30),
	AGE NUMBER(2),
	PRIMARY KEY(ID)
);
CREATE TABLE CHILDREN
(
	PARENT_ID NUMBER(4),
	NAME VARCHAR2(30),
	AGE NUMBER(2),
	PRIMARY KEY(PARENT_ID, NAME),
	FOREIGN KEY (PARENT_ID) REFERENCES PARENTS(ID)
);
